apiVersion: v1
kind: ConfigMap
metadata:
  name: java-config-reload-configmap
data:
  config_develop.json: |
    {
        "current_env" : "gcp-development-minikube",
        "Directory_Type" : "folder",
        "Input_Environment_Type" : "gcs",
        "Input_Environment_Location" : "raw-data",
        "Output_Environment_Type" : "bigquery",
        "Output_Environment_Location" : "test_ds",
        "sleepIntervalMillis": 1000
    }
