apiVersion: v1
kind: ConfigMap
metadata:
  name: java-config-reload-configmap
data:
  config_develop.json: |
    { "dataset_codes": [
    "gcp-development-minikube,folder,1000",
    "aws-development-minikube,folder,1000"]
    }
